config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events do
    resources :staffs
  end
  
  resources :status
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :user
    has_many :staffs
    
    validates :title, presence: true
    validates :position, presence: true
    validates :date_of_event, presence: true
    validates :last_date_of_event, presence: true
    validates :city, presence: true
    validates :location, presence: true
    validates :description, presence: true
    validates :pay, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  
  validates :name, presence: true, on: :create
  validates :age, presence: true, on: :create
  validates :phone_number, presence: true, on: :create
  validates :email_address, presence: true, on: :create
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :staffs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :find_event, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @events = Event.all.order("created_at DESC")
    end
    
    def show
        @staff = Staff.new
    end
    
    def new
        @event = current_user.events.build
    end
    
    def create
        @event = current_user.events.build(event_params)
        
        if @event.save
            current_user.update_attribute(:has_event, 'true')
            redirect_to root_path 
        else
            render 'new' 
        end
    end
    
    def edit
    end
    
    def update
        if @event.update(event_params)
            redirect_to event_path(@event)
        else
            render 'edit'
        end
    end
    
    def destroy
        @event.destroy
        redirect_to root_path
    end
    
    private
        def event_params
            params.require(:event).permit(:title, :position, :date_of_event, 
                                          :last_date_of_event, :location, :pay, 
                                          :city, :description)
        end
        
        def find_event
            @event = Event.find(params[:id])
        end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
    before_action :authenticate_user!
    
    def new
        @event = Event.find(params[:event_id])
        @staff = @event.staffs.build
    end
    
    def index
        @staffs = Staff.all
    end
    
    def create
        @event = Event.find(params[:event_id])
        @staff = @event.staffs.create(staff_params)
        @staff.user_id = current_user.id
        
        if @staff.save 
            redirect_to root_path
        else
            render 'events/show'
        end
    end

    private
        def staff_params
            params.require(:staff).permit(:name, :age, :phone_number, :email_address)
        end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @staffs = Staff.all
    end
    
    def show
        @event = Event.find(params[:id])
        @staff = @event.staffs
    end
    
    def destroy
       @staff = Staff.find(params[:id])
       @event = @staff.event
       @staff.destroy
       redirect_to status_path(@event)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
    <%= f.input :title, placeholder: "Name of Event" %>
    <%= f.input :position, label: "Looking for", placeholder: "Ex. Korean Bilinguals, Driver, Production Assistant, etc.." %>
    <%= f.input :date_of_event, as: :date, html5: :true, label: "Start date" %>
    <%= f.input :last_date_of_event, as: :date, html5: :true, label: "End date" %>
    <%= f.input :city, placeholder: "Ex. San Francisco" %>
    <%= f.input :location, placeholder: "Name of venue" %>
    <%= f.input :description, label: "Preferences and/or Requirements", 
                        placeholder: "-- Must be 25 years of age or older
-- Must have a valid driver license
-- Must be able to drive a 15 passenger van
-- Previous TV/film production experience preferred, but not a must
-- Familiar with greater SF or Seattle area" %>
    <%= f.input :pay, label: "Pay per day", placeholder: "Ex. 100" %>
    <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<h2>Edit the Event</h2>

<%= render 'form' %>

app/views/events/index.html.erb
<% @events.each do |event| %>
    <div class="col-md-4">
        <div class="message">
            <p class="message-title"> <%= event.title %></p>    
            <%= link_to "View Event", event_path(event), class: "btn-custom" %>
        </div>
    </div>
<% end %>

app/views/events/new.html.erb
<div class="col-md-8 col-md-offset-2">

    <h2>Create an Event</h2>
    
    <%= render 'form' %>
    
</div>

app/views/events/show.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="message-show">
        <h2><%= @event.title %></h2>
        <p class="message-posted-by">Created by <%= @event.user.email %> <%= time_ago_in_words(@event.created_at) %> ago</p>
        <p>Looking for: <%= @event.position %></p>
        <p>Starting date: <%= @event.date_of_event %></p>
        <p>Ending date: <%= @event.last_date_of_event %></p>
        <p>City: <%= @event.city %></p>
        <p>Name of venue: <%= @event.location %></p>
        <p>Additional information/preferences/requirements: </p>
        <p><%= @event.description %></p>
        <p>Pay per day: <%= @event.pay %></p>
        
        <h3 class="reply-to-msg">Sign up form:</h3>
        <%= render 'staffs/form' %>
        
        <div class="links btn-group">
            <%= link_to "Back", root_path, class: "btn btn-default" %>
            <% if user_signed_in? %>
                <% if current_user.id == @event.user_id %>
                    <%= link_to "Edit", edit_event_path(@event), class: "btn btn-default" %>
                    <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
                <% end %>
            <% end %>
        </div>    
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
</head>
<body>
  
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Event Board", root_path, class: "navbar-brand" %>
      </div>
      
      <ul class="navbar-nav nav">
        <li><%= link_to "Add Event", new_event_path %></li>
				<% if user_signed_in? && current_user.has_event? %>
  				<li class="dropdown">
  					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Status <span class="caret"></span></a>
  					<ul class="dropdown-menu" role="menu">
  						<% Event.all.each do |event| %>
  						  <% if event.user_id == current_user.id %>
    								<li><%= link_to event.title, status_path(event), class: "link" %></li>
    						<% end %>
  						<% end %>
  					</ul>
  				</li>
				<% end %>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
			</ul>
    </div>
  </div
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
    <div id="error_explanation">
         <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/staffs/_form.html.erb
<%= simple_form_for([@event, @staff]) do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :phone_number %>
    <%= f.input :email_address %>
    <%= f.button :submit, "Submit" %>
<% end %>

app/views/staffs/new.html.erb
<h1>Complete the form</h1>

<%= render 'form' %>

app/views/status/show.html.erb
<h3>List of Volunteers for <%= @event.title %>:</h3>

<p><%= link_to "Event page", event_path(@event) %></p>

<table>
    <th>Name</th>
    <th>Age</th>
    <th>Phone Number</th>
    <th>Email Address</th>
    <th>Delete</th>
    <% @staff.each do |staff| %></h4>
        <tr>
            <td><%= staff.name %></td>
            <td><%= staff.age %></td>
            <td><%= staff.phone_number %></td>
            <td><%= staff.email_address %></td>
            <td><%= link_to "Delete", status_path(staff), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
    <% end %>
</table>

 